### ISSUE TITLE
Does not work if running from Synology with Docker

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [natpuch/web-pdf-toolbox#22]
I have a Synology DS918+ with Docker running. I created a Stack and deployed it successfully

```
---
version: '3.3'
services:
    web-pdf-toolbox:
        container_name: webpdf
        ports:
            - 25568:80
        environment:
            - PUID=1026
            - PGID=100
            - TZ=Europe/Berlin
        labels:
            - deunhealth.restart.on.unhealthy=true
        volumes:
            - /volume1/docker/webpdf:/tmp/pdf/
        restart: always
        image: zpex/web-pdf-toolbox
networks:
  default:
    name: dockernet
    external: true
```
The ` /volume1/docker/webpdf` is the folder on my Synology. Upload doesn't work. Whenever I try to upload, a folder is created in `stay_login=1;` . It looks like this on my Synology: `/volume1/docker/webpdf/stay_login=1;/` . 

I changed
```
volumes:
    pdf:/tmp/pdf/
```
so, that docker creates a volume by itself. Still same problem: I still get a folder `stay_login=1;`, but this time inside the pdf-Volume docker created. I spun um my Ubuntu-VM on VirtualBox and deployed via docker-compose:

```
---
version: '3.3'
services:
    web-pdf-toolbox:
        container_name: webpdftoolbox
        ports:
            - 25568:80
        environment:
            - PUID=1026
            - PGID=100
            - TZ=Europe/Berlin
        labels:
            - deunhealth.restart.on.unhealthy=true
        volumes:
            - pdf:/tmp/pdf/
        restart: always
        image: zpex/web-pdf-toolbox
volumes:
  pdf:
```

tested it and it works. Why doesn't it work on my Synology?
